name: Pull Request Open

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  # PR open and close use the same group, allowing only one at a time
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"
          server-id: "github"

      - name: Removing old core
        uses: paulushcgcj/delete-github-package@1.0.0
        continue-on-error: true
        with:
          token: ${{ secrets.PAT }}
          type: gradle
          name: com.alfafa.gradle-demo-groovy
          version: 1.0.0
          user: ${{ github.repository_owner }}

      - name: Publish Core
        uses: paulushcgcj/action-java-publish@v0.0.5
        with:
          commands: echo 1.0.0
          dir: .
          app-version: 1.0.0
          java-cache: gradle
          java-distribution: temurin
          java-version: "17"
        env:
          GITHUB_TOKEN: ${{ github.token }}